Traceback (most recent call last):
  File "./script/experiment/GenerateDescriptorFile.py", line 282, in <module>
    main()
  File "./script/experiment/GenerateDescriptorFile.py", line 204, in main
    loaded = torch.load(used_file, map_location=map_location)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: ''
